version: "2"
services:
  rabbitmq:
    container_name: rabbitmq
    #image: rabbitmq:management
    image: heidiks/rabbitmq-delayed-message-exchange
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
