version: '2'
services:

    mysql:
        image: mysql:5.6
        expose:
            - "3306"
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: always

