version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: qianjiang
      MONGO_INITDB_ROOT_PASSWORD: mongodb_!!_iot
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db